- hosts: all
  become: yes
  tasks:
    - name: doc
      community.docker.docker_container:
        name: doc
        image: wordpress:latest
        ports:
          - "9090:80"
        volumes:
          - wordpress-www:/var/www/html
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "exampleuser"
          WORDPRESS_DB_PASSWORD: "examplepass"
          WORDPRESS_DB_NAME: "exampledb"
        restart_policy: always
        labels:
          traefik.http.routers.doc.rule: "Host(`doc.headshed.dev`)"
          traefik.http.routers.doc.tls: "true"
          traefik.http.routers.doc.tls.certresolver: "myresolver"
        networks:
          - name: "traefik"

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        volumes:
          - wordpress-db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "exampledb"
          MYSQL_USER: "exampleuser"
          MYSQL_PASSWORD: "examplepass"
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        restart_policy: always
        networks:
          - name: "traefik"





