- hosts: all
  become: yes
  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: traefik
    - name: traefik-reverse-proxy
      community.docker.docker_container:
        name: traefik
        image: traefik:v2.10
        command:
          - "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--certificatesresolvers.myresolver.acme.email=your-marshyon@gmail.com"
          - "--certificatesresolvers.myresolver.acme.storage=acme.json"
          - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
          - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "traefik-letsencrypt:/letsencrypt"
        networks:
          - name: "traefik"
        restart_policy: always

    - name: whoami
      community.docker.docker_container:
        name: whoami
        # image: nginx
        image: traefik/whoami
        labels:
          traefik.http.routers.whoami.rule: "Host(`whoami.headshed.dev`)"
          traefik.http.routers.whoami.tls: "true"
          traefik.http.routers.whoami.tls.certresolver: "myresolver"
        networks:
          - name: "traefik"



